/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.68
 * Generated at: 2022-10-21 18:38:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import curso.java.tienda.pojo.Producto;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/layouts/header.jspf", Long.valueOf(1666362967903L));
    _jspx_dependants.put("/WEB-INF/layouts/footer.jspf", Long.valueOf(1666362661603L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("curso.java.tienda.pojo.Producto");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("	<!-- Meta Tag -->\r\n");
      out.write("	<meta charset=\"utf-8\">\r\n");
      out.write("	<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("	<meta name='copyright' content=''>\r\n");
      out.write("	<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("	<meta name=\"viewport\"\r\n");
      out.write("		content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("	<!-- Title Tag  -->\r\n");
      out.write("	<title>Tienda Carlos Picado Esteban</title>\r\n");
      out.write("	<!-- Favicon -->\r\n");
      out.write("	<link rel=\"icon\" type=\"image/png\" href=\"assets/images/favicon.png\">\r\n");
      out.write("	<!-- Web Font -->\r\n");
      out.write("	<link\r\n");
      out.write("		href=\"https://fonts.googleapis.com/css?family=Poppins:200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i&display=swap\"\r\n");
      out.write("		rel=\"stylesheet\">\r\n");
      out.write("	\r\n");
      out.write("	<!-- StyleSheet -->\r\n");
      out.write("	\r\n");
      out.write("	<!-- Bootstrap -->\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"assets/css/bootstrap.css\">\r\n");
      out.write("	<!-- Magnific Popup -->\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"assets/css/magnific-popup.min.css\">\r\n");
      out.write("	<!-- Font Awesome -->\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"assets/css/font-awesome.css\">\r\n");
      out.write("	<!-- Fancybox -->\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"assets/css/jquery.fancybox.min.css\">\r\n");
      out.write("	<!-- Themify Icons -->\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"assets/css/themify-icons.css\">\r\n");
      out.write("	<!-- Nice Select CSS -->\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"assets/css/niceselect.css\">\r\n");
      out.write("	<!-- Animate CSS -->\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"assets/css/animate.css\">\r\n");
      out.write("	<!-- Flex Slider CSS -->\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"assets/css/flex-slider.min.css\">\r\n");
      out.write("	<!-- Owl Carousel -->\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"assets/css/owl-carousel.css\">\r\n");
      out.write("	<!-- Slicknav -->\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"assets/css/slicknav.min.css\">\r\n");
      out.write("	\r\n");
      out.write("	<!-- Eshop StyleSheet -->\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"assets/css/reset.css\">\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"assets/style.css\">\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"assets/css/responsive.css\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<body class=\"js\">\r\n");
      out.write("\r\n");
      out.write("	<!-- Preloader -->\r\n");
      out.write("	<div class=\"preloader\">\r\n");
      out.write("		<div class=\"preloader-inner\">\r\n");
      out.write("			<div class=\"preloader-icon\">\r\n");
      out.write("				<span></span> <span></span>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- End Preloader -->\r\n");
      out.write("\r\n");
      out.write("	<!-- Header -->\r\n");
      out.write("	<header class=\"header shop\">\r\n");
      out.write("		<!-- Topbar -->\r\n");
      out.write("		<div class=\"topbar\">\r\n");
      out.write("			<div class=\"container\">\r\n");
      out.write("				<div class=\"row\">\r\n");
      out.write("					<div class=\"col-lg-4 col-md-12 col-12\">\r\n");
      out.write("						<!-- Top Left -->\r\n");
      out.write("						<div class=\"top-left\">\r\n");
      out.write("							<ul class=\"list-main\">\r\n");
      out.write("								<li><i class=\"ti-headphone-alt\"></i> +060 (800) 801-582</li>\r\n");
      out.write("								<li><i class=\"ti-email\"></i> support@shophub.com</li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</div>\r\n");
      out.write("						<!--/ End Top Left -->\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"col-lg-8 col-md-12 col-12\">\r\n");
      out.write("						<!-- Top Right -->\r\n");
      out.write("						<div class=\"right-content\">\r\n");
      out.write("							<ul class=\"list-main\">\r\n");
      out.write("								<li><i class=\"ti-location-pin\"></i> Store location</li>\r\n");
      out.write("								<li><i class=\"ti-alarm-clock\"></i> <a href=\"#\">Daily\r\n");
      out.write("										deal</a></li>\r\n");
      out.write("								<li><i class=\"ti-user\"></i> <a href=\"#\">My account</a></li>\r\n");
      out.write("								<li><i class=\"ti-power-off\"></i><a href=\"login\">Login</a></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</div>\r\n");
      out.write("						<!-- End Top Right -->\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- End Topbar -->\r\n");
      out.write("		<div class=\"middle-inner\">\r\n");
      out.write("			<div class=\"container\">\r\n");
      out.write("				<div class=\"row\">\r\n");
      out.write("					<div class=\"col-lg-2 col-md-2 col-12\">\r\n");
      out.write("						<!-- Logo -->\r\n");
      out.write("						<div class=\"logo\">\r\n");
      out.write("							<a href=\"index.html\"><img src=\"assets/images/logo.png\"\r\n");
      out.write("								alt=\"logo\"></a>\r\n");
      out.write("						</div>\r\n");
      out.write("						<!--/ End Logo -->\r\n");
      out.write("						<!-- Search Form -->\r\n");
      out.write("						<div class=\"search-top\">\r\n");
      out.write("							<div class=\"top-search\">\r\n");
      out.write("								<a href=\"#0\"><i class=\"ti-search\"></i></a>\r\n");
      out.write("							</div>\r\n");
      out.write("							<!-- Search Form -->\r\n");
      out.write("							<div class=\"search-top\">\r\n");
      out.write("								<form class=\"search-form\">\r\n");
      out.write("									<input type=\"text\" placeholder=\"Search here...\" name=\"search\">\r\n");
      out.write("									<button value=\"search\" type=\"submit\">\r\n");
      out.write("										<i class=\"ti-search\"></i>\r\n");
      out.write("									</button>\r\n");
      out.write("								</form>\r\n");
      out.write("							</div>\r\n");
      out.write("							<!--/ End Search Form -->\r\n");
      out.write("						</div>\r\n");
      out.write("						<!--/ End Search Form -->\r\n");
      out.write("						<div class=\"mobile-nav\"></div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"col-lg-8 col-md-7 col-12\">\r\n");
      out.write("						<div class=\"search-bar-top\">\r\n");
      out.write("							<div class=\"search-bar\">\r\n");
      out.write("								<select>\r\n");
      out.write("									<option selected=\"selected\">All Category</option>\r\n");
      out.write("									<option>watch</option>\r\n");
      out.write("									<option>mobile</option>\r\n");
      out.write("									<option>kid’s item</option>\r\n");
      out.write("								</select>\r\n");
      out.write("								<form>\r\n");
      out.write("									<input name=\"search\" placeholder=\"Search Products Here.....\"\r\n");
      out.write("										type=\"search\">\r\n");
      out.write("									<button class=\"btnn\">\r\n");
      out.write("										<i class=\"ti-search\"></i>\r\n");
      out.write("									</button>\r\n");
      out.write("								</form>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"col-lg-2 col-md-3 col-12\">\r\n");
      out.write("						<div class=\"right-bar\">\r\n");
      out.write("							<!-- Search Form -->\r\n");
      out.write("							<div class=\"sinlge-bar\">\r\n");
      out.write("								<a href=\"#\" class=\"single-icon\"><i class=\"fa fa-heart-o\"\r\n");
      out.write("									aria-hidden=\"true\"></i></a>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"sinlge-bar\">\r\n");
      out.write("								<a href=\"#\" class=\"single-icon\"><i\r\n");
      out.write("									class=\"fa fa-user-circle-o\" aria-hidden=\"true\"></i></a>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"sinlge-bar shopping\">\r\n");
      out.write("								<a href=\"#\" class=\"single-icon\"><i class=\"ti-bag\"></i> <span\r\n");
      out.write("									class=\"total-count\">2</span></a>\r\n");
      out.write("								<!-- Shopping Item -->\r\n");
      out.write("								<div class=\"shopping-item\">\r\n");
      out.write("									<div class=\"dropdown-cart-header\">\r\n");
      out.write("										<span>2 Items</span> <a href=\"#\">View Carrito</a>\r\n");
      out.write("									</div>\r\n");
      out.write("									<ul class=\"shopping-list\">\r\n");
      out.write("										<li><a href=\"#\" class=\"remove\" title=\"Remove this item\"><i\r\n");
      out.write("												class=\"fa fa-remove\"></i></a> <a class=\"cart-img\" href=\"#\"><img\r\n");
      out.write("												src=\"https://via.placeholder.com/70x70\" alt=\"#\"></a>\r\n");
      out.write("											<h4>\r\n");
      out.write("												<a href=\"#\">Woman Ring</a>\r\n");
      out.write("											</h4>\r\n");
      out.write("											<p class=\"quantity\">\r\n");
      out.write("												1x - <span class=\"amount\">$99.00</span>\r\n");
      out.write("											</p></li>\r\n");
      out.write("										<li><a href=\"#\" class=\"remove\" title=\"Remove this item\"><i\r\n");
      out.write("												class=\"fa fa-remove\"></i></a> <a class=\"cart-img\" href=\"#\"><img\r\n");
      out.write("												src=\"https://via.placeholder.com/70x70\" alt=\"#\"></a>\r\n");
      out.write("											<h4>\r\n");
      out.write("												<a href=\"#\">Woman Necklace</a>\r\n");
      out.write("											</h4>\r\n");
      out.write("											<p class=\"quantity\">\r\n");
      out.write("												1x - <span class=\"amount\">$35.00</span>\r\n");
      out.write("											</p></li>\r\n");
      out.write("									</ul>\r\n");
      out.write("									<div class=\"bottom\">\r\n");
      out.write("										<div class=\"total\">\r\n");
      out.write("											<span>Total</span> <span class=\"total-amount\">$134.00</span>\r\n");
      out.write("										</div>\r\n");
      out.write("										<a href=\"checkout.html\" class=\"btn animate\">Checkout</a>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("								<!--/ End Shopping Item -->\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- Header Inner -->\r\n");
      out.write("		<div class=\"header-inner\">\r\n");
      out.write("			<div class=\"container\">\r\n");
      out.write("				<div class=\"cat-nav-head\">\r\n");
      out.write("					<div class=\"row\">\r\n");
      out.write("						<div class=\"col-lg-3\">\r\n");
      out.write("							<div class=\"all-category\">\r\n");
      out.write("								<h3 class=\"cat-heading\">\r\n");
      out.write("									<i class=\"fa fa-bars\" aria-hidden=\"true\"></i>CATEGORIAS\r\n");
      out.write("								</h3>\r\n");
      out.write("								<ul class=\"main-category\">\r\n");
      out.write("									<li><a href=\"#\">New Arrivals <i\r\n");
      out.write("											class=\"fa fa-angle-right\" aria-hidden=\"true\"></i></a>\r\n");
      out.write("										<ul class=\"sub-category\">\r\n");
      out.write("											<li><a href=\"#\">accessories</a></li>\r\n");
      out.write("											<li><a href=\"#\">best selling</a></li>\r\n");
      out.write("											<li><a href=\"#\">top 100 offer</a></li>\r\n");
      out.write("											<li><a href=\"#\">sunglass</a></li>\r\n");
      out.write("											<li><a href=\"#\">watch</a></li>\r\n");
      out.write("											<li><a href=\"#\">man’s product</a></li>\r\n");
      out.write("											<li><a href=\"#\">ladies</a></li>\r\n");
      out.write("											<li><a href=\"#\">westrn dress</a></li>\r\n");
      out.write("											<li><a href=\"#\">denim </a></li>\r\n");
      out.write("										</ul></li>\r\n");
      out.write("									<li class=\"main-mega\"><a href=\"#\">best selling <i\r\n");
      out.write("											class=\"fa fa-angle-right\" aria-hidden=\"true\"></i></a>\r\n");
      out.write("										<ul class=\"mega-menu\">\r\n");
      out.write("											<li class=\"single-menu\"><a href=\"#\" class=\"title-link\">Shop\r\n");
      out.write("													Kid's</a>\r\n");
      out.write("												<div class=\"image\">\r\n");
      out.write("													<img src=\"https://via.placeholder.com/225x155\" alt=\"#\">\r\n");
      out.write("												</div>\r\n");
      out.write("												<div class=\"inner-link\">\r\n");
      out.write("													<a href=\"#\">Kids Toys</a> <a href=\"#\">Kids Travel Car</a> <a\r\n");
      out.write("														href=\"#\">Kids Color Shape</a> <a href=\"#\">Kids Tent</a>\r\n");
      out.write("												</div></li>\r\n");
      out.write("											<li class=\"single-menu\"><a href=\"#\" class=\"title-link\">Shop\r\n");
      out.write("													Men's</a>\r\n");
      out.write("												<div class=\"image\">\r\n");
      out.write("													<img src=\"https://via.placeholder.com/225x155\" alt=\"#\">\r\n");
      out.write("												</div>\r\n");
      out.write("												<div class=\"inner-link\">\r\n");
      out.write("													<a href=\"#\">Watch</a> <a href=\"#\">T-shirt</a> <a href=\"#\">Hoodies</a>\r\n");
      out.write("													<a href=\"#\">Formal Pant</a>\r\n");
      out.write("												</div></li>\r\n");
      out.write("											<li class=\"single-menu\"><a href=\"#\" class=\"title-link\">Shop\r\n");
      out.write("													Women's</a>\r\n");
      out.write("												<div class=\"image\">\r\n");
      out.write("													<img src=\"https://via.placeholder.com/225x155\" alt=\"#\">\r\n");
      out.write("												</div>\r\n");
      out.write("												<div class=\"inner-link\">\r\n");
      out.write("													<a href=\"#\">Ladies Shirt</a> <a href=\"#\">Ladies Frog</a> <a\r\n");
      out.write("														href=\"#\">Ladies Sun Glass</a> <a href=\"#\">Ladies Watch</a>\r\n");
      out.write("												</div></li>\r\n");
      out.write("										</ul></li>\r\n");
      out.write("									<li><a href=\"#\">accessories</a></li>\r\n");
      out.write("									<li><a href=\"#\">top 100 offer</a></li>\r\n");
      out.write("									<li><a href=\"#\">sunglass</a></li>\r\n");
      out.write("									<li><a href=\"#\">watch</a></li>\r\n");
      out.write("									<li><a href=\"#\">man’s product</a></li>\r\n");
      out.write("									<li><a href=\"#\">ladies</a></li>\r\n");
      out.write("									<li><a href=\"#\">westrn dress</a></li>\r\n");
      out.write("									<li><a href=\"#\">denim </a></li>\r\n");
      out.write("								</ul>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-lg-9 col-12\">\r\n");
      out.write("							<div class=\"menu-area\">\r\n");
      out.write("								<!-- Main Menu -->\r\n");
      out.write("								<nav class=\"navbar navbar-expand-lg\">\r\n");
      out.write("									<div class=\"navbar-collapse\">\r\n");
      out.write("										<div class=\"nav-inner\">\r\n");
      out.write("											<ul class=\"nav main-menu menu navbar-nav\">\r\n");
      out.write("												<li class=\"active\"><a href=\"#\">Home</a></li>\r\n");
      out.write("												<li><a href=\"#\">Product</a></li>\r\n");
      out.write("												<li><a href=\"#\">Service</a></li>\r\n");
      out.write("												<li><a href=\"#\">Shop<i class=\"ti-angle-down\"></i><span\r\n");
      out.write("														class=\"new\">New</span></a>\r\n");
      out.write("													<ul class=\"dropdown\">\r\n");
      out.write("														<li><a href=\"shop-grid.html\">Shop Grid</a></li>\r\n");
      out.write("														<li><a href=\"cart.html\">Cart</a></li>\r\n");
      out.write("														<li><a href=\"checkout.html\">Checkout</a></li>\r\n");
      out.write("													</ul></li>\r\n");
      out.write("												<li><a href=\"#\">Pages</a></li>\r\n");
      out.write("												<li><a href=\"#\">Blog<i class=\"ti-angle-down\"></i></a>\r\n");
      out.write("													<ul class=\"dropdown\">\r\n");
      out.write("														<li><a href=\"blog-single-sidebar.html\">Blog\r\n");
      out.write("																Single Sidebar</a></li>\r\n");
      out.write("													</ul></li>\r\n");
      out.write("												<li><a href=\"contact.html\">Contact Us</a></li>\r\n");
      out.write("											</ul>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("								</nav>\r\n");
      out.write("								<!--/ End Main Menu -->\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<!--/ End Header Inner -->\r\n");
      out.write("	</header>\r\n");
      out.write("	<!--/ End Header -->\r\n");
      out.write("\r\n");
      out.write("	<!-- Slider Area -->\r\n");
      out.write("	<section class=\"hero-slider\">\r\n");
      out.write("		<!-- Single Slider -->\r\n");
      out.write("		<div class=\"single-slider\">\r\n");
      out.write("			<div class=\"container\">\r\n");
      out.write("				<div class=\"row no-gutters\">\r\n");
      out.write("					<div class=\"col-lg-9 offset-lg-3 col-12\">\r\n");
      out.write("						<div class=\"text-inner\">\r\n");
      out.write("							<div class=\"row\">\r\n");
      out.write("								<div class=\"col-lg-7 col-12\">\r\n");
      out.write("									<div class=\"hero-text\">\r\n");
      out.write("										<h1>\r\n");
      out.write("											<span>UP TO 50% OFF </span>Shirt For Man\r\n");
      out.write("										</h1>\r\n");
      out.write("										<p>\r\n");
      out.write("											Maboriosam in a nesciung eget magnae <br> dapibus\r\n");
      out.write("											disting tloctio in the find it pereri <br> odiy\r\n");
      out.write("											maboriosm.\r\n");
      out.write("										</p>\r\n");
      out.write("										<div class=\"button\">\r\n");
      out.write("											<a href=\"#\" class=\"btn\">Shop Now!</a>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<!--/ End Single Slider -->\r\n");
      out.write("	</section>\r\n");
      out.write("	<!--/ End Slider Area -->\r\n");
      out.write("\r\n");
      out.write("	<!-- Start Most Popular -->\r\n");
      out.write("	<div class=\"product-area most-popular section\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-12\">\r\n");
      out.write("					<div class=\"section-title\">\r\n");
      out.write("						<h2>Nuestro catálogo</h2>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-12\">\r\n");
      out.write("					<div class=\"owl-carousel popular-slider\">\r\n");
      out.write("\r\n");
      out.write("			");
 ArrayList<Producto> listaProductos = (ArrayList<Producto>) request.getAttribute("listaProductos"); 
      out.write("\r\n");
      out.write("\r\n");
      out.write("			");
 for (Producto producto : listaProductos) { 
      out.write("\r\n");
      out.write("	\r\n");
      out.write("						<div class=\"single-product\">\r\n");
      out.write("							<div class=\"product-img\">\r\n");
      out.write("								<a href=\"product-details.html\"> <img class=\"default-img\"\r\n");
      out.write("									src=\"productos/");
      out.print( producto.getId() );
      out.write(".jpg\" alt=\"#\"> <img\r\n");
      out.write("									class=\"hover-img\" src=\"https://via.placeholder.com/550x750\"\r\n");
      out.write("									alt=\"#\">\r\n");
      out.write("								</a>\r\n");
      out.write("								<div class=\"button-head\">\r\n");
      out.write("									<div class=\"product-action\">\r\n");
      out.write("										<a data-toggle=\"modal\" data-target=\"#exampleModal\"\r\n");
      out.write("											title=\"Quick View\" href=\"#\"><i class=\" ti-eye\"></i><span>Quick\r\n");
      out.write("												Shop</span></a> <a title=\"Wishlist\" href=\"#\"><i class=\" ti-heart \"></i><span>Add\r\n");
      out.write("												to Wishlist</span></a> <a title=\"Compare\" href=\"#\"><i\r\n");
      out.write("											class=\"ti-bar-chart-alt\"></i><span>Add to Compare</span></a>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"product-action-2\">\r\n");
      out.write("										<a title=\"Add to cart\" href=\"#\">Add to cart</a>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"product-content\">\r\n");
      out.write("								<h3>\r\n");
      out.write("									<a href=\"product-details.html\">");
      out.print( producto.getNombre() );
      out.write("</a>\r\n");
      out.write("								</h3>\r\n");
      out.write("								<div class=\"product-price\">\r\n");
      out.write("									<span>");
      out.print( producto.getPrecio() );
      out.write("</span>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("			");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- End Most Popular Area -->\r\n");
      out.write("\r\n");
      out.write("	<!-- Start Shop Services Area -->\r\n");
      out.write("	<section class=\"shop-services section home\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-lg-3 col-md-6 col-12\">\r\n");
      out.write("					<!-- Start Single Service -->\r\n");
      out.write("					<div class=\"single-service\">\r\n");
      out.write("						<i class=\"ti-rocket\"></i>\r\n");
      out.write("						<h4>Free shiping</h4>\r\n");
      out.write("						<p>Orders over $100</p>\r\n");
      out.write("					</div>\r\n");
      out.write("					<!-- End Single Service -->\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-lg-3 col-md-6 col-12\">\r\n");
      out.write("					<!-- Start Single Service -->\r\n");
      out.write("					<div class=\"single-service\">\r\n");
      out.write("						<i class=\"ti-reload\"></i>\r\n");
      out.write("						<h4>Free Return</h4>\r\n");
      out.write("						<p>Within 30 days returns</p>\r\n");
      out.write("					</div>\r\n");
      out.write("					<!-- End Single Service -->\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-lg-3 col-md-6 col-12\">\r\n");
      out.write("					<!-- Start Single Service -->\r\n");
      out.write("					<div class=\"single-service\">\r\n");
      out.write("						<i class=\"ti-lock\"></i>\r\n");
      out.write("						<h4>Sucure Payment</h4>\r\n");
      out.write("						<p>100% secure payment</p>\r\n");
      out.write("					</div>\r\n");
      out.write("					<!-- End Single Service -->\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-lg-3 col-md-6 col-12\">\r\n");
      out.write("					<!-- Start Single Service -->\r\n");
      out.write("					<div class=\"single-service\">\r\n");
      out.write("						<i class=\"ti-tag\"></i>\r\n");
      out.write("						<h4>Best Peice</h4>\r\n");
      out.write("						<p>Guaranteed price</p>\r\n");
      out.write("					</div>\r\n");
      out.write("					<!-- End Single Service -->\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</section>\r\n");
      out.write("	<!-- End Shop Services Area -->\r\n");
      out.write("\r\n");
      out.write("	<!-- Start Shop Newsletter  -->\r\n");
      out.write("	<section class=\"shop-newsletter section\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"inner-top\">\r\n");
      out.write("				<div class=\"row\">\r\n");
      out.write("					<div class=\"col-lg-8 offset-lg-2 col-12\">\r\n");
      out.write("						<!-- Start Newsletter Inner -->\r\n");
      out.write("						<div class=\"inner\">\r\n");
      out.write("							<h4>Newsletter</h4>\r\n");
      out.write("							<p>\r\n");
      out.write("								Subscribe to our newsletter and get <span>10%</span> off your\r\n");
      out.write("								first purchase\r\n");
      out.write("							</p>\r\n");
      out.write("							<form action=\"mail/mail.php\" method=\"get\" target=\"_blank\"\r\n");
      out.write("								class=\"newsletter-inner\">\r\n");
      out.write("								<input name=\"EMAIL\" placeholder=\"Your email address\" required=\"\"\r\n");
      out.write("									type=\"email\">\r\n");
      out.write("								<button class=\"btn\">Subscribe</button>\r\n");
      out.write("							</form>\r\n");
      out.write("						</div>\r\n");
      out.write("						<!-- End Newsletter Inner -->\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</section>\r\n");
      out.write("	<!-- End Shop Newsletter -->\r\n");
      out.write("\r\n");
      out.write("	<!-- Modal -->\r\n");
      out.write("	<div class=\"modal fade\" id=\"exampleModal\" tabindex=\"-1\" role=\"dialog\">\r\n");
      out.write("		<div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("			<div class=\"modal-content\">\r\n");
      out.write("				<div class=\"modal-header\">\r\n");
      out.write("					<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\r\n");
      out.write("						aria-label=\"Close\">\r\n");
      out.write("						<span class=\"ti-close\" aria-hidden=\"true\"></span>\r\n");
      out.write("					</button>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"modal-body\">\r\n");
      out.write("					<div class=\"row no-gutters\">\r\n");
      out.write("						<div class=\"col-lg-6 col-md-12 col-sm-12 col-xs-12\">\r\n");
      out.write("							<!-- Product Slider -->\r\n");
      out.write("							<div class=\"product-gallery\">\r\n");
      out.write("								<div class=\"quickview-slider-active\">\r\n");
      out.write("									<div class=\"single-slider\">\r\n");
      out.write("										<img src=\"https://via.placeholder.com/569x528\" alt=\"#\">\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"single-slider\">\r\n");
      out.write("										<img src=\"https://via.placeholder.com/569x528\" alt=\"#\">\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"single-slider\">\r\n");
      out.write("										<img src=\"https://via.placeholder.com/569x528\" alt=\"#\">\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"single-slider\">\r\n");
      out.write("										<img src=\"https://via.placeholder.com/569x528\" alt=\"#\">\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<!-- End Product slider -->\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-lg-6 col-md-12 col-sm-12 col-xs-12\">\r\n");
      out.write("							<div class=\"quickview-content\">\r\n");
      out.write("								<h2>Flared Shift Dress</h2>\r\n");
      out.write("								<div class=\"quickview-ratting-review\">\r\n");
      out.write("									<div class=\"quickview-ratting-wrap\">\r\n");
      out.write("										<div class=\"quickview-ratting\">\r\n");
      out.write("											<i class=\"yellow fa fa-star\"></i> <i\r\n");
      out.write("												class=\"yellow fa fa-star\"></i> <i class=\"yellow fa fa-star\"></i>\r\n");
      out.write("											<i class=\"yellow fa fa-star\"></i> <i class=\"fa fa-star\"></i>\r\n");
      out.write("										</div>\r\n");
      out.write("										<a href=\"#\"> (1 customer review)</a>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"quickview-stock\">\r\n");
      out.write("										<span><i class=\"fa fa-check-circle-o\"></i> in stock</span>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("								<h3>$29.00</h3>\r\n");
      out.write("								<div class=\"quickview-peragraph\">\r\n");
      out.write("									<p>Lorem ipsum dolor sit amet, consectetur adipisicing\r\n");
      out.write("										elit. Mollitia iste laborum ad impedit pariatur esse optio\r\n");
      out.write("										tempora sint ullam autem deleniti nam in quos qui nemo ipsum\r\n");
      out.write("										numquam.</p>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"size\">\r\n");
      out.write("									<div class=\"row\">\r\n");
      out.write("										<div class=\"col-lg-6 col-12\">\r\n");
      out.write("											<h5 class=\"title\">Size</h5>\r\n");
      out.write("											<select>\r\n");
      out.write("												<option selected=\"selected\">s</option>\r\n");
      out.write("												<option>m</option>\r\n");
      out.write("												<option>l</option>\r\n");
      out.write("												<option>xl</option>\r\n");
      out.write("											</select>\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"col-lg-6 col-12\">\r\n");
      out.write("											<h5 class=\"title\">Color</h5>\r\n");
      out.write("											<select>\r\n");
      out.write("												<option selected=\"selected\">orange</option>\r\n");
      out.write("												<option>purple</option>\r\n");
      out.write("												<option>black</option>\r\n");
      out.write("												<option>pink</option>\r\n");
      out.write("											</select>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"quantity\">\r\n");
      out.write("									<!-- Input Order -->\r\n");
      out.write("									<div class=\"input-group\">\r\n");
      out.write("										<div class=\"button minus\">\r\n");
      out.write("											<button type=\"button\" class=\"btn btn-primary btn-number\"\r\n");
      out.write("												disabled=\"disabled\" data-type=\"minus\" data-field=\"quant[1]\">\r\n");
      out.write("												<i class=\"ti-minus\"></i>\r\n");
      out.write("											</button>\r\n");
      out.write("										</div>\r\n");
      out.write("										<input type=\"text\" name=\"quant[1]\" class=\"input-number\"\r\n");
      out.write("											data-min=\"1\" data-max=\"1000\" value=\"1\">\r\n");
      out.write("										<div class=\"button plus\">\r\n");
      out.write("											<button type=\"button\" class=\"btn btn-primary btn-number\"\r\n");
      out.write("												data-type=\"plus\" data-field=\"quant[1]\">\r\n");
      out.write("												<i class=\"ti-plus\"></i>\r\n");
      out.write("											</button>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("									<!--/ End Input Order -->\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"add-to-cart\">\r\n");
      out.write("									<a href=\"#\" class=\"btn\">Add to cart</a> <a href=\"#\"\r\n");
      out.write("										class=\"btn min\"><i class=\"ti-heart\"></i></a> <a href=\"#\"\r\n");
      out.write("										class=\"btn min\"><i class=\"fa fa-compress\"></i></a>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"default-social\">\r\n");
      out.write("									<h4 class=\"share-now\">Share:</h4>\r\n");
      out.write("									<ul>\r\n");
      out.write("										<li><a class=\"facebook\" href=\"#\"><i\r\n");
      out.write("												class=\"fa fa-facebook\"></i></a></li>\r\n");
      out.write("										<li><a class=\"twitter\" href=\"#\"><i\r\n");
      out.write("												class=\"fa fa-twitter\"></i></a></li>\r\n");
      out.write("										<li><a class=\"youtube\" href=\"#\"><i\r\n");
      out.write("												class=\"fa fa-pinterest-p\"></i></a></li>\r\n");
      out.write("										<li><a class=\"dribbble\" href=\"#\"><i\r\n");
      out.write("												class=\"fa fa-google-plus\"></i></a></li>\r\n");
      out.write("									</ul>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- Modal end -->\r\n");
      out.write("\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<!-- Start Footer Area -->\r\n");
      out.write("<footer class=\"footer\">\r\n");
      out.write("	<!-- Footer Top -->\r\n");
      out.write("	<div class=\"footer-top section\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-lg-5 col-md-6 col-12\">\r\n");
      out.write("					<!-- Single Widget -->\r\n");
      out.write("					<div class=\"single-footer about\">\r\n");
      out.write("						<div class=\"logo\">\r\n");
      out.write("							<a href=\"index.html\"><img src=\"assets/images/logo2.png\"\r\n");
      out.write("								alt=\"#\"></a>\r\n");
      out.write("						</div>\r\n");
      out.write("						<p class=\"text\">Praesent dapibus, neque id cursus ucibus,\r\n");
      out.write("							tortor neque egestas augue, magna eros eu erat. Aliquam erat\r\n");
      out.write("							volutpat. Nam dui mi, tincidunt quis, accumsan porttitor,\r\n");
      out.write("							facilisis luctus, metus.</p>\r\n");
      out.write("						<p class=\"call\">\r\n");
      out.write("							Got Question? Call us 24/7<span><a href=\"tel:123456789\">+0123\r\n");
      out.write("									456 789</a></span>\r\n");
      out.write("						</p>\r\n");
      out.write("					</div>\r\n");
      out.write("					<!-- End Single Widget -->\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-lg-2 col-md-6 col-12\">\r\n");
      out.write("					<!-- Single Widget -->\r\n");
      out.write("					<div class=\"single-footer links\">\r\n");
      out.write("						<h4>Information</h4>\r\n");
      out.write("						<ul>\r\n");
      out.write("							<li><a href=\"#\">About Us</a></li>\r\n");
      out.write("							<li><a href=\"#\">Faq</a></li>\r\n");
      out.write("							<li><a href=\"#\">Terms & Conditions</a></li>\r\n");
      out.write("							<li><a href=\"#\">Contact Us</a></li>\r\n");
      out.write("							<li><a href=\"#\">Help</a></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("					<!-- End Single Widget -->\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-lg-2 col-md-6 col-12\">\r\n");
      out.write("					<!-- Single Widget -->\r\n");
      out.write("					<div class=\"single-footer links\">\r\n");
      out.write("						<h4>Customer Service</h4>\r\n");
      out.write("						<ul>\r\n");
      out.write("							<li><a href=\"#\">Payment Methods</a></li>\r\n");
      out.write("							<li><a href=\"#\">Money-back</a></li>\r\n");
      out.write("							<li><a href=\"#\">Returns</a></li>\r\n");
      out.write("							<li><a href=\"#\">Shipping</a></li>\r\n");
      out.write("							<li><a href=\"#\">Privacy Policy</a></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("					<!-- End Single Widget -->\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-lg-3 col-md-6 col-12\">\r\n");
      out.write("					<!-- Single Widget -->\r\n");
      out.write("					<div class=\"single-footer social\">\r\n");
      out.write("						<h4>Get In Tuch</h4>\r\n");
      out.write("						<!-- Single Widget -->\r\n");
      out.write("						<div class=\"contact\">\r\n");
      out.write("							<ul>\r\n");
      out.write("								<li>NO. 342 - London Oxford Street.</li>\r\n");
      out.write("								<li>012 United Kingdom.</li>\r\n");
      out.write("								<li>info@eshop.com</li>\r\n");
      out.write("								<li>+032 3456 7890</li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</div>\r\n");
      out.write("						<!-- End Single Widget -->\r\n");
      out.write("						<ul>\r\n");
      out.write("							<li><a href=\"#\"><i class=\"ti-facebook\"></i></a></li>\r\n");
      out.write("							<li><a href=\"#\"><i class=\"ti-twitter\"></i></a></li>\r\n");
      out.write("							<li><a href=\"#\"><i class=\"ti-flickr\"></i></a></li>\r\n");
      out.write("							<li><a href=\"#\"><i class=\"ti-instagram\"></i></a></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("					<!-- End Single Widget -->\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- End Footer Top -->\r\n");
      out.write("	<div class=\"copyright\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"inner\">\r\n");
      out.write("				<div class=\"row\">\r\n");
      out.write("					<div class=\"col-lg-6 col-12\">\r\n");
      out.write("						<div class=\"left\">\r\n");
      out.write("							<p>\r\n");
      out.write("								Copyright © 2020 <a href=\"http://www.wpthemesgrid.com\"\r\n");
      out.write("									target=\"_blank\">Wpthemesgrid</a> - All Rights Reserved.\r\n");
      out.write("							</p>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"col-lg-6 col-12\">\r\n");
      out.write("						<div class=\"right\">\r\n");
      out.write("							<img src=\"assets/images/payments.png\" alt=\"#\">\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</footer>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("<!-- /End Footer Area -->\r\n");
      out.write("\r\n");
      out.write("<!-- Jquery -->\r\n");
      out.write("<script src=\"assets/js/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"assets/js/jquery-migrate-3.0.0.js\"></script>\r\n");
      out.write("<script src=\"assets/js/jquery-ui.min.js\"></script>\r\n");
      out.write("<!-- Popper JS -->\r\n");
      out.write("<script src=\"assets/js/popper.min.js\"></script>\r\n");
      out.write("<!-- Bootstrap JS -->\r\n");
      out.write("<script src=\"assets/js/bootstrap.min.js\"></script>\r\n");
      out.write("<!-- Slicknav JS -->\r\n");
      out.write("<script src=\"assets/js/slicknav.min.js\"></script>\r\n");
      out.write("<!-- Owl Carousel JS -->\r\n");
      out.write("<script src=\"assets/js/owl-carousel.js\"></script>\r\n");
      out.write("<!-- Magnific Popup JS -->\r\n");
      out.write("<script src=\"assets/js/magnific-popup.js\"></script>\r\n");
      out.write("<!-- Waypoints JS -->\r\n");
      out.write("<script src=\"assets/js/waypoints.min.js\"></script>\r\n");
      out.write("<!-- Countdown JS -->\r\n");
      out.write("<script src=\"assets/js/finalcountdown.min.js\"></script>\r\n");
      out.write("<!-- Nice Select JS -->\r\n");
      out.write("<script src=\"assets/js/nicesellect.js\"></script>\r\n");
      out.write("<!-- Flex Slider JS -->\r\n");
      out.write("<script src=\"assets/js/flex-slider.js\"></script>\r\n");
      out.write("<!-- ScrollUp JS -->\r\n");
      out.write("<script src=\"assets/js/scrollup.js\"></script>\r\n");
      out.write("<!-- Onepage Nav JS -->\r\n");
      out.write("<script src=\"assets/js/onepage-nav.min.js\"></script>\r\n");
      out.write("<!-- Easing JS -->\r\n");
      out.write("<script src=\"assets/js/easing.js\"></script>\r\n");
      out.write("<!-- Active JS -->\r\n");
      out.write("<script src=\"assets/js/active.js\"></script>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
