/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.68
 * Generated at: 2022-10-21 18:53:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/layouts/header.jspf", Long.valueOf(1666362967903L));
    _jspx_dependants.put("/WEB-INF/layouts/footer.jspf", Long.valueOf(1666362661603L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("	<!-- Meta Tag -->\r\n");
      out.write("	<meta charset=\"utf-8\">\r\n");
      out.write("	<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("	<meta name='copyright' content=''>\r\n");
      out.write("	<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("	<meta name=\"viewport\"\r\n");
      out.write("		content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("	<!-- Title Tag  -->\r\n");
      out.write("	<title>Tienda Carlos Picado Esteban</title>\r\n");
      out.write("	<!-- Favicon -->\r\n");
      out.write("	<link rel=\"icon\" type=\"image/png\" href=\"assets/images/favicon.png\">\r\n");
      out.write("	<!-- Web Font -->\r\n");
      out.write("	<link\r\n");
      out.write("		href=\"https://fonts.googleapis.com/css?family=Poppins:200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i&display=swap\"\r\n");
      out.write("		rel=\"stylesheet\">\r\n");
      out.write("	\r\n");
      out.write("	<!-- StyleSheet -->\r\n");
      out.write("	\r\n");
      out.write("	<!-- Bootstrap -->\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"assets/css/bootstrap.css\">\r\n");
      out.write("	<!-- Magnific Popup -->\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"assets/css/magnific-popup.min.css\">\r\n");
      out.write("	<!-- Font Awesome -->\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"assets/css/font-awesome.css\">\r\n");
      out.write("	<!-- Fancybox -->\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"assets/css/jquery.fancybox.min.css\">\r\n");
      out.write("	<!-- Themify Icons -->\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"assets/css/themify-icons.css\">\r\n");
      out.write("	<!-- Nice Select CSS -->\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"assets/css/niceselect.css\">\r\n");
      out.write("	<!-- Animate CSS -->\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"assets/css/animate.css\">\r\n");
      out.write("	<!-- Flex Slider CSS -->\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"assets/css/flex-slider.min.css\">\r\n");
      out.write("	<!-- Owl Carousel -->\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"assets/css/owl-carousel.css\">\r\n");
      out.write("	<!-- Slicknav -->\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"assets/css/slicknav.min.css\">\r\n");
      out.write("	\r\n");
      out.write("	<!-- Eshop StyleSheet -->\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"assets/css/reset.css\">\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"assets/style.css\">\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"assets/css/responsive.css\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container-fluid p-0\">\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<!-- Start Footer Area -->\r\n");
      out.write("<footer class=\"footer\">\r\n");
      out.write("	<!-- Footer Top -->\r\n");
      out.write("	<div class=\"footer-top section\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-lg-5 col-md-6 col-12\">\r\n");
      out.write("					<!-- Single Widget -->\r\n");
      out.write("					<div class=\"single-footer about\">\r\n");
      out.write("						<div class=\"logo\">\r\n");
      out.write("							<a href=\"index.html\"><img src=\"assets/images/logo2.png\"\r\n");
      out.write("								alt=\"#\"></a>\r\n");
      out.write("						</div>\r\n");
      out.write("						<p class=\"text\">Praesent dapibus, neque id cursus ucibus,\r\n");
      out.write("							tortor neque egestas augue, magna eros eu erat. Aliquam erat\r\n");
      out.write("							volutpat. Nam dui mi, tincidunt quis, accumsan porttitor,\r\n");
      out.write("							facilisis luctus, metus.</p>\r\n");
      out.write("						<p class=\"call\">\r\n");
      out.write("							Got Question? Call us 24/7<span><a href=\"tel:123456789\">+0123\r\n");
      out.write("									456 789</a></span>\r\n");
      out.write("						</p>\r\n");
      out.write("					</div>\r\n");
      out.write("					<!-- End Single Widget -->\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-lg-2 col-md-6 col-12\">\r\n");
      out.write("					<!-- Single Widget -->\r\n");
      out.write("					<div class=\"single-footer links\">\r\n");
      out.write("						<h4>Information</h4>\r\n");
      out.write("						<ul>\r\n");
      out.write("							<li><a href=\"#\">About Us</a></li>\r\n");
      out.write("							<li><a href=\"#\">Faq</a></li>\r\n");
      out.write("							<li><a href=\"#\">Terms & Conditions</a></li>\r\n");
      out.write("							<li><a href=\"#\">Contact Us</a></li>\r\n");
      out.write("							<li><a href=\"#\">Help</a></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("					<!-- End Single Widget -->\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-lg-2 col-md-6 col-12\">\r\n");
      out.write("					<!-- Single Widget -->\r\n");
      out.write("					<div class=\"single-footer links\">\r\n");
      out.write("						<h4>Customer Service</h4>\r\n");
      out.write("						<ul>\r\n");
      out.write("							<li><a href=\"#\">Payment Methods</a></li>\r\n");
      out.write("							<li><a href=\"#\">Money-back</a></li>\r\n");
      out.write("							<li><a href=\"#\">Returns</a></li>\r\n");
      out.write("							<li><a href=\"#\">Shipping</a></li>\r\n");
      out.write("							<li><a href=\"#\">Privacy Policy</a></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("					<!-- End Single Widget -->\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-lg-3 col-md-6 col-12\">\r\n");
      out.write("					<!-- Single Widget -->\r\n");
      out.write("					<div class=\"single-footer social\">\r\n");
      out.write("						<h4>Get In Tuch</h4>\r\n");
      out.write("						<!-- Single Widget -->\r\n");
      out.write("						<div class=\"contact\">\r\n");
      out.write("							<ul>\r\n");
      out.write("								<li>NO. 342 - London Oxford Street.</li>\r\n");
      out.write("								<li>012 United Kingdom.</li>\r\n");
      out.write("								<li>info@eshop.com</li>\r\n");
      out.write("								<li>+032 3456 7890</li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</div>\r\n");
      out.write("						<!-- End Single Widget -->\r\n");
      out.write("						<ul>\r\n");
      out.write("							<li><a href=\"#\"><i class=\"ti-facebook\"></i></a></li>\r\n");
      out.write("							<li><a href=\"#\"><i class=\"ti-twitter\"></i></a></li>\r\n");
      out.write("							<li><a href=\"#\"><i class=\"ti-flickr\"></i></a></li>\r\n");
      out.write("							<li><a href=\"#\"><i class=\"ti-instagram\"></i></a></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("					<!-- End Single Widget -->\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- End Footer Top -->\r\n");
      out.write("	<div class=\"copyright\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"inner\">\r\n");
      out.write("				<div class=\"row\">\r\n");
      out.write("					<div class=\"col-lg-6 col-12\">\r\n");
      out.write("						<div class=\"left\">\r\n");
      out.write("							<p>\r\n");
      out.write("								Copyright © 2020 <a href=\"http://www.wpthemesgrid.com\"\r\n");
      out.write("									target=\"_blank\">Wpthemesgrid</a> - All Rights Reserved.\r\n");
      out.write("							</p>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"col-lg-6 col-12\">\r\n");
      out.write("						<div class=\"right\">\r\n");
      out.write("							<img src=\"assets/images/payments.png\" alt=\"#\">\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</footer>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("<!-- /End Footer Area -->\r\n");
      out.write("\r\n");
      out.write("<!-- Jquery -->\r\n");
      out.write("<script src=\"assets/js/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"assets/js/jquery-migrate-3.0.0.js\"></script>\r\n");
      out.write("<script src=\"assets/js/jquery-ui.min.js\"></script>\r\n");
      out.write("<!-- Popper JS -->\r\n");
      out.write("<script src=\"assets/js/popper.min.js\"></script>\r\n");
      out.write("<!-- Bootstrap JS -->\r\n");
      out.write("<script src=\"assets/js/bootstrap.min.js\"></script>\r\n");
      out.write("<!-- Slicknav JS -->\r\n");
      out.write("<script src=\"assets/js/slicknav.min.js\"></script>\r\n");
      out.write("<!-- Owl Carousel JS -->\r\n");
      out.write("<script src=\"assets/js/owl-carousel.js\"></script>\r\n");
      out.write("<!-- Magnific Popup JS -->\r\n");
      out.write("<script src=\"assets/js/magnific-popup.js\"></script>\r\n");
      out.write("<!-- Waypoints JS -->\r\n");
      out.write("<script src=\"assets/js/waypoints.min.js\"></script>\r\n");
      out.write("<!-- Countdown JS -->\r\n");
      out.write("<script src=\"assets/js/finalcountdown.min.js\"></script>\r\n");
      out.write("<!-- Nice Select JS -->\r\n");
      out.write("<script src=\"assets/js/nicesellect.js\"></script>\r\n");
      out.write("<!-- Flex Slider JS -->\r\n");
      out.write("<script src=\"assets/js/flex-slider.js\"></script>\r\n");
      out.write("<!-- ScrollUp JS -->\r\n");
      out.write("<script src=\"assets/js/scrollup.js\"></script>\r\n");
      out.write("<!-- Onepage Nav JS -->\r\n");
      out.write("<script src=\"assets/js/onepage-nav.min.js\"></script>\r\n");
      out.write("<!-- Easing JS -->\r\n");
      out.write("<script src=\"assets/js/easing.js\"></script>\r\n");
      out.write("<!-- Active JS -->\r\n");
      out.write("<script src=\"assets/js/active.js\"></script>");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
